#!/usr/bin/env python3
"""Write generation report: lineage tree, pass counts, best genome, baseline vs evolved holdout."""

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from research_evolver.src.utils.config_loader import get_db_path, get_artifacts_root
from research_evolver.src.memory import (
    get_connection,
    get_generation_summaries,
    get_all_lineages,
    get_experiment,
    get_best_survivors,
)


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate lineage and generation report")
    ap.add_argument("--generation", type=int, default=None, help="Latest generation if not set")
    ap.add_argument("--dashboard", action="store_true", help="Write dashboard.html")
    args = ap.parse_args()

    db_path = get_db_path()
    if not db_path.exists():
        print("DB not found: %s. Run init_db and at least one generation." % db_path)
        return 1
    conn = get_connection(str(db_path))

    summaries = get_generation_summaries(conn)
    if not summaries:
        print("No generation summaries in DB.")
        conn.close()
        return 0
    latest_gen = max(s[0] for s in summaries) if summaries else 0
    gen_idx = args.generation if args.generation is not None else latest_gen

    report_dir = get_artifacts_root() / "reports"
    report_dir.mkdir(parents=True, exist_ok=True)

    # --- Text report ---
    report_path = report_dir / "lineage_report.txt"
    lines = [
        "Research Evolver — Lineage & Generation Report",
        "=" * 60,
        "",
        "Generation summaries (population -> s1 -> s2 -> s3, best_fitness):",
        "",
    ]
    for row in summaries:
        gen, pop, s1, s2, s3, best, cost = row
        lines.append("  gen %d: pop=%d -> s1=%d -> s2=%d -> s3=%d  best_fitness=%s  cost=%s" % (
            gen, pop or 0, s1 or 0, s2 or 0, s3 or 0, best if best is not None else "N/A", cost or 0
        ))
    lines.extend(["", "Lineages (founder -> best_experiment_id, generations_alive):", ""])
    for row in get_all_lineages(conn):
        lid, founder, best_exp, alive, stag = row
        lines.append("  %s  founder=%s  best=%s  gens_alive=%d  stagnation=%d" % (
            lid, founder, best_exp or "—", alive or 0, stag or 0
        ))
    lines.extend(["", "Best experiments for generation %d (stage3):" % gen_idx, ""])
    survivors = get_best_survivors(conn, gen_idx, "stage3", limit=5)
    for exp_id, genome_json, fitness in survivors:
        lines.append("  %s  fitness=%s" % (exp_id, fitness))
    lines.append("")
    with open(report_path, "w") as f:
        f.write("\n".join(lines))
    print("Report written to %s" % report_path)

    # --- Simple HTML dashboard ---
    if args.dashboard:
        html_path = report_dir / "dashboard.html"
        rows = []
        for row in summaries:
            gen, pop, s1, s2, s3, best, cost = row
            best_str = "%.4f" % best if best is not None else "—"
            rows.append("<tr><td>%d</td><td>%d</td><td>%d</td><td>%d</td><td>%d</td><td>%s</td><td>%s</td></tr>" % (
                gen, pop or 0, s1 or 0, s2 or 0, s3 or 0, best_str, cost or 0
            ))
        lineage_rows = []
        for row in get_all_lineages(conn):
            lid, founder, best_exp, alive, stag = row
            lineage_rows.append("<tr><td>%s</td><td>%s</td><td>%s</td><td>%d</td><td>%d</td></tr>" % (
                lid, founder, best_exp or "—", alive or 0, stag or 0
            ))
        html = """<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Research Evolver Dashboard</title>
<style>body{font-family:sans-serif;margin:1rem;} table{border-collapse:collapse;} th,td{border:1px solid #ccc;padding:6px 10px;} th{background:#eee;}</style></head>
<body>
<h1>Research Evolver Dashboard</h1>
<h2>Generation summary</h2>
<table>
<tr><th>gen</th><th>pop</th><th>s1</th><th>s2</th><th>s3</th><th>best_fitness</th><th>cost</th></tr>
%s
</table>
<h2>Lineages</h2>
<table>
<tr><th>lineage_id</th><th>founder_id</th><th>best_experiment_id</th><th>generations_alive</th><th>stagnation</th></tr>
%s
</table>
<p><small>Generated by make_report.py --dashboard</small></p>
</body></html>""" % ("\n".join(rows), "\n".join(lineage_rows))
        with open(html_path, "w") as f:
            f.write(html)
        print("Dashboard written to %s" % html_path)

    conn.close()
    return 0


if __name__ == "__main__":
    sys.exit(main())
